language: python
sudo: required
python:
    - "2.7"
env: PGVERSION=9.2
cache: pip
install:
    - bash bin/travis-build.bash
    - pip install coveralls
script:
  - sh bin/travis-run.sh
  - pycodestyle --count ./ckanext/tayside
after_success:
    - coveralls
